<template>
<div>
<h2> Recording Studio Services</h2>
<p>IPSUM DOLOR SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMFUSCE EUISMOD CONSEQUAT ANTE. LOREM IPSUM DOLOR SIT AMET, CONSECTETUER ADIPISCING ELIT. PELLENTESQUE SED DOLOR. ALIQUAM CONGUE FERMENTUM NISL. MAURIS ACCUMSAN NULLA VEL DIAM. SED IN LACUS UT ENIM ADIPISCING ALIQUET. NULLA VENENATIS. IN PEDE MI, ALIQUET SIT AMET, EUISMOD IN</p>
<h3>MASTERING</h3>
<p>PSUM DOLOR SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMFUSCE EUISMOD CONSEQUAT ANTE. LOREM IPSUM DOLOR SIT AMET, CONSECTETUER ADIPISCING ELIT. PELLENTESQUE SED DOLOR. ALIQUAM CONGUE FERMENTUM NISL. MAURIS ACCUMSAN NULLA VEL DIAM. SED IN LACUS UT ENIM ADIPISCING ALIQUET. NULLA VENENATIS. IN PEDE MI, ALIQUET SIT AMET, EUISMOD IN</p>
    <div class="row">
        <div class="col-md-6 px-4 ">
            <img src="imgs/mixer.gif" style="opacity: .6" class="img-fluid" alt="An image of a music producer mixer">
        </div>
        <div class="col-md-6">
            <h3>PRODUCTION</h3>
            <p>PSUM DOLOR SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMFUSCE EUISMOD CONSEQUAT ANTE. LOREM IPSUM DOLOR SIT AMET,</p>
        </div>
    </div>
    <h3>ADDITIONAL FEES</h3>
    <p>PSUM DOLOR SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMFUSCE EUISMOD CONSEQUAT ANTE. LOREM IPSUM DOLOR SIT AMET</p>
    <div class="row">
        <div class="col-md-6">
            <h3>MIXING TRACKS FROM ANOTHER RECORDING STUDIO</h3>
            <p>PSUM DOLOR SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMFUSCE EUISMOD CONSEQUAT ANTE. LOREM IPSUM DOLOR SIT AMET,</p>
        </div>
        <div class="col-md-6 px-4">
            <img src="imgs/music-studio-mic.gif" class="img-fluid" style="opacity: .7" alt="An image of a music producer mixer">
        </div>
    </div>
</div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>
